version: '3.8'

services:
  # Container 1: MySQL Database
  mysqldb:
    image: mysql:8.0
    container_name: foodcourt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodcourt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Data save rakhne ke liye agar db restart ho

  # Container 2: Aapki Spring Boot App
  restaurant-api:
    build: . # Ye usi folder ki Dockerfile ko run karega
    container_name: foodcourt_api
    depends_on:
      - mysqldb # Ensure karta hai ki pehle DB start ho
    ports:
      - "8080:8080"
    environment:
      # Yahan hum application.properties ko override kar rahe hain
      # Notice karein 'localhost' ki jagah maine 'mysqldb' (service name) likha hai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/foodcourt_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

# Volumes define karna taaki MySQL ka data delete na ho
volumes:
  db_data: